name: PR commenter

on:
  push:
    branches:
      - 'main'

# This grants access to the GITHUB_TOKEN so the action can make calls to GitHub's rest API
permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  pr-version-comment:
    runs-on: ubuntu-latest
    name: pr-version-comment
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # This action needs the entire history of the repository to calculate the version
          fetch-depth: 0
      - name: Run comment action
        uses: AsgerIversen/pr-version-comment@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: This change is part of OpenTAP version `{version}` or later.
          issue-body: A fix for this is in OpenTAP version `{version}` or later.